Login do sistema
ES-231-gp2/backend pull request #9
Opened 2023-10-21 20:10 UTC by lleones

AMOOOOOO

2023-10-21 20:41 UTC, JonatasTavaresS requested changes
Algumas mudanças.

2023-10-21 20:41 UTC, JonatasTavaresS commented on src/main/java/com/ufcg/es/biblioconex/controller/LoginController.java
> +            @RequestParam String login, @RequestParam String senha) {
Não funcionou aqui, não entendi porque recebe login e senha no link e no corpo da requisição, deixar apenas no corpo.
```suggestion
             {
```

2023-10-21 20:41 UTC, JonatasTavaresS commented on src/main/java/com/ufcg/es/biblioconex/model/Usuario.java
> +    private String login;
O `login` deveria ser definido como `email`, como está na documentação. Tem uma notação `@Email` de validação.

2023-10-21 20:41 UTC, JonatasTavaresS commented on src/main/java/com/ufcg/es/biblioconex/model/Usuario.java
> +    private String login;
Login deveria ser `email` como está nas especificações. Tem a notação `@Email` para validação.

2023-10-21 20:41 UTC, JonatasTavaresS commented on src/main/java/com/ufcg/es/biblioconex/model/Usuario.java
> +    private TipoUsuarioEnum tipoUsuario;
Adicionar notação `@Enumerated(EnumType.STRING)`

2023-10-21 20:41 UTC, JonatasTavaresS commented on src/main/java/com/ufcg/es/biblioconex/service/UsuarioServiceImpl.java
> +    public Usuario cadastrarUsuario(String login, String senha, UsuarioDTO usuarioDTO) {
Faltam validações de outros tipos de usuário, e é necessário passar o enumerate e não a string.

2023-10-21 20:59 UTC, lleones commented on src/main/java/com/ufcg/es/biblioconex/controller/LoginController.java
> +            @RequestParam String login, @RequestParam String senha) {
é pedido 2 vezes pq o do DTO é o que vai ser inserido na tabela e os do corpo são as de autenticação. Porque só o bibliotecario cadastra. Alterei os nomes pra "loginBibliotecário" e "senhaBibliotecario" pra ficar mais claro

2023-10-21 21:01 UTC, lleones commented on src/main/java/com/ufcg/es/biblioconex/service/UsuarioServiceImpl.java
> +    public Usuario cadastrarUsuario(String login, String senha, UsuarioDTO usuarioDTO) {
O tipo do usuário é validado no service de usuário, lançando uma UsuarioNaoAutorizadoException. O enumerate não é passado pq ele ta dentrod o DTO.

2023-10-21 22:02 UTC, JonatasTavaresS commented on src/main/java/com/ufcg/es/biblioconex/model/Usuario.java
> +    @Column(nullable = false)
Tá permitindo cadastrar usuário com mesmo e-mail.
```suggestion
    @Column(nullable = false, unique = true)
```

2023-10-23 12:44 UTC, JonatasTavaresS approved these changes

2023-10-23 12:45 UTC, merged